### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by fredpeertje** [RS-Coop/Applied-Deep-Learning-1#1]
I tried to run your main.py script on the semanticKITTI dataset with the pretrained models from [here](https://hanlab.mit.edu/files/SPVNAS/spvnas_specialized/SemanticKITTI_val_SPVNAS@20GMACs/). However, I get the following error:

`RuntimeError: The size of tensor a (90127) must match the size of tensor b (90065) at non-singleton dimension 0`
Starting at line:
`miou, _ = E.evaluate(model, dataset, dataroot, device, split=split) `

What pretrained model did you use?

**Comment by RS-Coop** [comment]
To answer your question simply, I used the same pre-trained model as you specify in your link. However, I am not aware of any problems like what you have encountered.

It seems I have significantly broken something on my end, so I will need a bit of time to fix a few things before I can try to figure out your error. I will get back to you soon though.

Can you give me more details on your setup (e.g. torch version)?

**Comment by fredpeertje** [comment]
Thank you for the quick response. These are the versions of the most important libraries…

```
pip install --upgrade git+https://github.com/mit-han-lab/torchsparse.git@v1.0.0 
libsparsehash-dev (2.0.2-1)
torch (1.7.1+cu101)
nuscenes-devkit (1.1.2)
```

Another thing, when I use the most recent version of torchsparse I get the following error earlier (I just run the small eval.ipynb):
`RuntimeError: running_mean should contain 1000 elements not 20`
Starting at line:
`model = SPVStd(net_config, params, device)`

**Comment by RS-Coop** [comment]
It looks like torchsparse have made some recent changes which have broken things on my end, so currently I am not able to try and figure out your original problem. I have opened an issue there to try and figure it out. As for the running_mean error, I am not quite sure what the problem is based on that RuntimeError output, so I will have to look at it on my end once everything with torchsparse is sorted.

I am not entirely sure when I will be able to fix these problems, but I will get back to you when I do. In the meantime I would be happy to help with or talk about anything else. This project (as you have seen) is very much a work in progress, but hopefully I can help you get out of it what you were looking for.

**Comment by fredpeertje** [comment]
The most recent version of torchparse also broke the code in the official spvnas repo. So for that one, you have to use @v1.0.0.

Thank you. This is much appreciated!

**Comment by fredpeertje** [comment]
Update:
Changed some configurations in evaluate.py according to SPVNAS repo (spvnas/configs/semantic_kitti/default.yaml):
```
ignore_label = 255
voxel_size = 0.05
batch_size = 2
num_workers = 4
```

Unfortunately, same error:
`RuntimeError: The size of tensor a ...`

**Comment by fredpeertje** [comment]
Hi, the issue was caused by not properly loading the semanticKITTI dataset. Therefore, I made a mix between your code and the e3d code. A snippet that fixed my issue:

```
    def evaluate(self, model, dataroot, device, map_labels=False):
        #Reset for mIOU calculations
        self.reset()

        dataset = builder.make_dataset()

        dataflow_val = torch.utils.data.DataLoader(
            dataset["test"],
            batch_size=1, # Only for train use configs.batch_size
            num_workers=4,
            pin_memory=True,
            collate_fn=dataset["test"].collate_fn)

        model.eval()

        with torch.no_grad():
```
